version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      args:
        REACT_APP_API_ENDPOINT: https://api.domeinbeschrijving.hbo-i.nl
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hbo-i-fe.entrypoints=websecure"
      - "traefik.http.routers.hbo-i-fe.rule=Host(`domeinbeschrijving.hbo-i.nl`)"
      - "traefik.http.routers.hbo-i-fe.tls=true"
      - "traefik.http.routers.hbo-i-fe.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
